### ISSUE TITLE
Was "www.google.com" purposefully added?

### ISSUE THREAD

**Issue by Thomas-Schubert** [tg12/pihole-phishtank-list#1]
It blocks the search engine entirely.

**Comment by tg12** [comment]
Short answer is no.    It is possible to host malicious content on many google domains (docs.google.com and drive.google.com are quite prolific).       Google has domains where you can’t host content, but you can create URLs that redirect else where to locations that do host malicious content.

 It wouldn’t surprise me if there were a few exceptions in the list that could be whitelisted, but whitelisting *.google.com across the board will create false negatives.

The solution is to whitelist this in Pi-hole then it wont be an issue.
