### ISSUE TITLE
s3.amazonaws.com shouldn't be blocked

### ISSUE THREAD

**Issue by elderlabs** [tg12/pihole-phishtank-list#15]
`s3.amazonaws.com` is a user-generated content delivery network. While _some_ shady content may originate from the CDN, many legitimate sites use content hosted here. As such, it causes an issue with many websites. Instead of blacklisting the entire CDN, it is recommended to block individual sites hosting malicious content instead. At the very least, the site should be added to the "consider whitelisting" list.

**Comment by tg12** [comment]
You are right, This has been whitelisted and will be fixed in the next release.
