### ISSUE TITLE
encrypted-tbn0.gstatic.com blocked

### ISSUE THREAD

**Issue by krbrs** [tg12/pihole-phishtank-list#17]
encrypted-tbn0.gstatic.com is a thumbnail domain from Google. 

This domain being blocked seems to cause thumbnails not showing on picture search and maybe other issues which I don't see yet. Other similiar domains e.g. encrypted-tbn3.gstatic.com are not blocked. Maybe this should be whitelisted.

**Comment by tg12** [comment]
I will fix this.

**Comment by tg12** [comment]
Done
