### ISSUE TITLE
invalid domains

### ISSUE THREAD

**Issue by 0n1cOn3** [tg12/pihole-phishtank-list#19]
Hi

im getting actually some invalid links, here the console output of PiHole:

  [i] Target: https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 2782 domains, 11 domains invalid!
      Sample of invalid domains:
      - yahoo%2eco%2ejp@bhgxa.eo76sni.cn
      - yahoo%2eco%2ejp@jhdd.fjcslad.cn
      - yahoo%2eco%2ejp@kjhdda.tetfeec.cn
      - yahoo%2eco%2ejp@lkjds.nlmwjta.cn
      - yahoo%2eco%2ejp@poklsa.slodddz.cn
  [i] List has been updated

**Comment by tg12** [comment]
These will be ignored anyway so it's fine to leave those.
