### ISSUE TITLE
gavity.list

### ISSUE THREAD

**Issue by pallebone** [tg12/pihole-phishtank-list#2]
Hi, thank you for this blocklist.

Can I also ask what is full_grav_list\gravity.list and can i use this list also as it has many domains, or is that list not really for that?

Kind regards
Peter

**Comment by tg12** [comment]
Hi, It's basically an amalgamation of all the most popular blocklists (including the ones you use in your projects by the looks of it). It's just a one size fits all including my Phishtank list. It gets pushed from my server and updated here whenever there is a change.

**Comment by pallebone** [comment]
Thank you. I appreciate your reply. I will try it out :)

Pete
