### ISSUE TITLE
Blank lines in phish_domains.txt causing a blocklist to block any matched url (which is all not whitelisted).

### ISSUE THREAD

**Issue by SystemJargon** [tg12/pihole-phishtank-list#21]
Issue is in the file https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt

Lines 38 and 2724 contains blank line/s or no entry. More the concern.

Also noted this too.

Line 89 contains the number "7" only.
Line 129 contains the number "0" only.

Based on blank lines, some users with AdGuard variants using this list or similar, may end up blocking ANY/ALL because the syntax of such easylists, use || in front, so in this example a blank with + "||" means any/all. Whitelist/allowlists circumvent the issue or other custom rules.

Yes, this is a pi-hole list, however would be nice to see the lines mentioned fixed up (thanks).

**Comment by tg12** [comment]
Thank you for bringing it to my attention, I will have a look at getting it fixed.

**Comment by tg12** [comment]
Please see the latest commit, I should have fixed all the issue. Apologies it's taken a while.
