### ISSUE TITLE
ci4.googleusercontent.com ci3.googleusercontent.com

### ISSUE THREAD

**Issue by p1r473** [tg12/pihole-phishtank-list#24]
This hosts GCP hosted static content 
Breaks images in Gmail
![image](https://user-images.githubusercontent.com/9235633/230409468-cf5dc0b5-37e3-4944-8f7b-400f0f601cd7.png)

**Comment by tg12** [comment]
Please see the latest commit, I should have fixed all the issue. Apologies it's taken a while.
