### ISSUE TITLE
Invalid domains on list

### ISSUE THREAD

**Issue by pallebone** [tg12/pihole-phishtank-list#25]
Hi there,

Thank you for this list. I notice pihole reports an error for some domains:

  [i] Target: https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 51643 exact domains and 0 ABP-style domains (ignored 4 non-domain entries)
      Sample of non-domain entries:
        - "0"
        - "johanneum-hamburg"
        - "padlet-uploads"

Kind regards
Peter

**Comment by pallebone** [comment]
Still appearing today:

  [i] Target: https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 51643 exact domains and 0 ABP-style domains (ignored 4 non-domain entries)
      Sample of non-domain entries:
        - "0"
        - "johanneum-hamburg"
        - "padlet-uploads"

**Comment by tg12** [comment]
Please see the latest commit, I should have fixed all the issue. Apologies it's taken a while.
