### ISSUE TITLE
www.google.com has been added to the list again

### ISSUE THREAD

**Issue by 32423676573** [tg12/pihole-phishtank-list#3]
Please stop adding www.google.com to your list. This is not a phishing site, and there is no benefit to explicitly add it in your list.

By blocking this it breaks a number of basic functionality; Android phones show connectivity issues, searching breaks,  google assistant wont work. Many core services that people depend on require that this is not blocked.

You cannot assume everyone will have manually whitelisted it to get around the issues with your list.

If this was a mistake, this is not the first time it has happened. Please be more careful when adding domains to your list as mistakes like this have far-reaching impact on anyone who relies on your list.

**Comment by jacklul** [comment]
www.dropbox.com also got blocked

This list is marked as safe https://firebog.net by @WaLLy3K so those domains shouldn't be blocked

**Comment by tg12** [comment]
Apologies for this, It's to do with the regex parsing, I have fixed this. It won't happen again. For both dropbox and google.

**Comment by jacklul** [comment]
I don't think `firebasestorage.googleapis.com` should be blocked either

Edit: `skydrivesync.policies.live.net` aswell (blocks OneDrive completely)

**Comment by tg12** [comment]
Apologies I've not seen this until now. This should be fixed now. Thanks for using this.
