### ISSUE TITLE
Error in pihole list

### ISSUE THREAD

**Issue by hiyan** [tg12/pihole-phishtank-list#4]
New subscriber to this list... getting this error when updating list in pihole

  [i] Target: https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt
  [✓] Status: Retrieval successful
  [i] Received 5774 domains, 21 domains invalid!
      Sample of invalid domains:
      - 113.161.144.143:8082
      - 141.193.196.75:84
      - 34.228.53.85:80
      - 35.196.197.52:80
      - appleverificationalert.com:443

**Comment by tg12** [comment]
PiHole is intelligent enough to ignore those errors, It happens with alot of other lists too and there is no detrimental impact to Pihole functionality as these entries are ignored. I could update my Regex to filter out the :port but for now it works. I will put it on my todo list. Thanks for mentioning it.
