### ISSUE TITLE
firebasestorage.googleapis.com shouldn't be blocked.

### ISSUE THREAD

**Issue by aravindvnair99** [tg12/pihole-phishtank-list#8]
Websites can't access Firebase Storage without this. Often media and other files are stored here. Breaks functionality on sites which use Firebase Storage.

**Comment by tg12** [comment]
Which domains do you want me to whitelist?

**Comment by aravindvnair99** [comment]
> Which domains do you want me to whitelist?

@tg12, `firebasestorage.googleapis.com` is the domain that should be whitelisted.

**Comment by tg12** [comment]
Resolved.
