### ISSUE TITLE
Sample of invalid domains

### ISSUE THREAD

**Issue by takenek** [tg12/pihole-phishtank-list#9]
hey,

  [i] Target: https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt
  [✓] Status: Retrieval successful
  [i] Received 5795 domains, 21 domains invalid!
      Sample of invalid domains:
      - 113.161.144.143:8082
      - 141.193.196.74:84
      - 141.193.196.75:84
      - appleverificationalert.com:443
      - doveadolescentservices-my.sharepoint.com:443

I think you can't put port in txt file ;-) and i saw you got in many places port...
root@test:~# grep ":" phish_domains.txt |wc -l
21

Best Regards
TaKeN

**Comment by tg12** [comment]
Hi, I believe this is now resolved.
